### ISSUE TITLE
some zip files after encoding will be Illegal judged by aliyundrive

### ISSUE THREAD

**Issue by Tsingkai** [ciscolxh/aliyunshare#1]
### File Infomations
files : OpenCV3.4.1 and OpenCV_3.4.1-contrib
software : maybe hao123zip ,Not I did this 

### Problem 
![image](https://user-images.githubusercontent.com/45168225/144553188-ce9bbfee-7718-4a2e-a4fe-4ede83868866.png)

I am going to change a software to compress file using another compress format.

**Comment by Tsingkai** [comment]
bandzip 6.26 & 7z failed, WTF!

**Comment by ciscolxh** [comment]
@Tsingkai 提交部分失败的文件发出来试一下我再调试一下

**Comment by Tsingkai** [comment]
> @Tsingkai 提交部分失败的文件发出来试一下我再调试一下

Uploading……
Check your QQ Email
